version: '3.3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8000:80
        networks:
            - search_app

    flask:
        container_name: flask_app
        build:
            context: .
            dockerfile: ./flask_app/Dockerfile
        command: bash -c "sleep 20 ;
                    python3 add_db.py ;
                    uwsgi --ini conf/uwsgi.ini"
        depends_on:
            - elasticsearch
        networks:
            - search_app

    db:
        image: postgres:14
        container_name: postgres
        environment:
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_DB: ${PSQL_DB}
            POSTGRES_PASSWORD: ${PSQL_PASS}
        volumes:
            - postgresql:/var/lib/postgresql/data
        networks:
            - search_app

    elasticsearch:
        image: elasticsearch:8.2.2
        container_name: elasticsearch
        depends_on:
            - db
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - node.name=elasticsearch
            - xpack.security.enabled=false
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        expose:
            - 9200
        networks:
            - search_app

volumes:
    postgresql:
    esdata:

networks:
    search_app:
